version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Autoconf/Automake
          command: aclocal && autoconf && automake --add-missing
      - run:
          name: Configure
          command: ./configure
      - run:
          name: Build
          command: make
